FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM alpine:3.20
WORKDIR /static
COPY --from=builder /app/dist/ /static/
CMD ["sh", "-c", "echo Static files are available in /static && ls -la /static"]
